<?php $this->headTitle()->append('Tech For Soluções em TI - Project'); ?>
<div id="content">
    <h1>Kanban Project</h1>
    <div class="">
        <form id="kanban" method="post">
            <table border="1">
                <tr>
                    <th>&nbsp;</ht>
                    <th>PROJECT</th>
                </tr>
                <?php foreach ($this->titles as $title): ?>
                    <tr>
                        <td><input type="checkbox" name="id_project[]" value="<?php echo $title['ID']; ?>">
                        <td><?php echo $title['ID'] . ' - ' . $title['pname']; ?></td>
                    <tr>
                <?php endforeach; ?>
            </table>
            <input type="submit" value="Enviar" />
        </form>
    </div>
</div>